[phases.setup]
aptPkgs = ["python3", "python3-pip", "ffmpeg", "libsm6", "libxext6"]
cmds = ["pip3 install --upgrade pip"]

[phases.build]
cmds = ["pip3 install -r requirements.txt"]

[phases.start]
cmds = ["pip3 install gunicorn", "gunicorn -b 0.0.0.0:8080 app:app"]
