[phases.setup]
aptPkgs = ["python3", "python3-pip", "ffmpeg", "libsm6", "libxext6"]
cmds = ["python3 -m ensurepip", "python3 -m pip install --upgrade pip"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmds = ["gunicorn -b 0.0.0.0:8080 app:app"]
